"""Adiciona data_criacao a Evento

Revision ID: 0313f1edbc65
Revises: 
Create Date: 2025-06-13 11:22:34.686869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0313f1edbc65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('console')
    op.drop_table('game')
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_evento', sa.Integer(), nullable=True))
        batch_op.alter_column('data_avaliacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'evento', ['id_evento'], ['id_evento'])

    with op.batch_alter_table('chatsuporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_resposta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('id_organizador', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('evento_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizador', ['id_organizador'], ['id_organizador'])
        batch_op.drop_column('idOrganizador')

    with op.batch_alter_table('organizador', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_usuario'])

    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_transacao', sa.String(length=100), nullable=True))
        batch_op.alter_column('data_pagamento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_reserva'])

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('data_de_reserva',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('reserva_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('idPagamento')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuario_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('usuario_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('idPagamento')
        batch_op.drop_column('idOrganizador')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idOrganizador', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idPagamento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('usuario_ibfk_2'), 'organizador', ['idOrganizador'], ['id_organizador'])
        batch_op.create_foreign_key(batch_op.f('usuario_ibfk_1'), 'pagamento', ['idPagamento'], ['id_pagamento'])

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idPagamento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('reserva_ibfk_2'), 'pagamento', ['idPagamento'], ['id_pagamento'])
        batch_op.alter_column('data_de_reserva',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('pagamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('data_pagamento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('codigo_transacao')

    with op.batch_alter_table('organizador', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idOrganizador', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('evento_ibfk_1'), 'organizador', ['idOrganizador'], ['id_organizador'])
        batch_op.drop_column('id_organizador')
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('chatsuporte', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('data_resposta')
        batch_op.drop_column('resposta')

    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('data_avaliacao',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('id_evento')

    op.create_table('game',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('ano', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('plataforma', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('preco', mysql.FLOAT(), nullable=True),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('console',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('fabricante', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('preco', mysql.FLOAT(), nullable=True),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
